apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
name: argo-demo
namespace: argocd

spec:
project: default

source:
repoURL: [https://github.com/yourgithubusername/ci-cd-argo-demo.git](https://github.com/yourgithubusername/ci-cd-argo-demo.git)
targetRevision: main
path: app

destination:
server: [https://kubernetes.default.svc](https://kubernetes.default.svc)
namespace: default

syncPolicy:
automated:
prune: true
selfHeal: true
